services:
  - type: web
    name: restaurant-booking
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn restaurant_booking.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
